#!/usr/bin/bash

export SCRIPT_DIR="${BASH_SOURCE[0]%/*}"
export PATH=${SCRIPT_DIR}:$PATH

set -x

./converter.rb &&
  generate.rb &&
  deploy.rb &&
  create_w3id.rb &&
  triplestore.rb &&
  echo "Completed successfully"
